// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int UserId { get; set; }

    public int ShowId { get; set; }

    public int NumberOfSeats { get; set; }

    public decimal TotalPrice { get; set; }

    public string Status { get; set; }

    public string QrcodeData { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual ICollection<BookedSeat> BookedSeats { get; set; } = new List<BookedSeat>();

    public virtual Payment Payment { get; set; }

    public virtual Show Show { get; set; }

    public virtual User User { get; set; }
}