// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Cinema
{
    public int CinemaId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int CityId { get; set; }

    public string ContactInfo { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual ICollection<CinemaHall> CinemaHalls { get; set; } = new List<CinemaHall>();

    public virtual City City { get; set; }
}