// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int UserId { get; set; }

    public int MovieId { get; set; }

    public string CommentText { get; set; }

    public int? ParentCommentId { get; set; }

    public bool? IsApproved { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual ICollection<Comment> InverseParentComment { get; set; } = new List<Comment>();

    public virtual Movie Movie { get; set; }

    public virtual Comment ParentComment { get; set; }

    public virtual User User { get; set; }
}