// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class MovieFavorite
{
    public int MovieFavoriteId { get; set; }

    public int UserId { get; set; }

    public int MovieId { get; set; }

    public DateTime? FavoriteTime { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User User { get; set; }
}