// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Duration { get; set; }

    public string Language { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public string TrailerUrl { get; set; }

    public string PosterUrl { get; set; }

    public decimal? Rating { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<MovieActor> MovieActors { get; set; } = new List<MovieActor>();

    public virtual ICollection<MovieDirector> MovieDirectors { get; set; } = new List<MovieDirector>();

    public virtual ICollection<MovieFavorite> MovieFavorites { get; set; } = new List<MovieFavorite>();

    public virtual ICollection<MovieGenre> MovieGenres { get; set; } = new List<MovieGenre>();

    public virtual ICollection<Show> Shows { get; set; } = new List<Show>();

    public virtual ICollection<Vote> Votes { get; set; } = new List<Vote>();
}