// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Person
{
    public int PersonId { get; set; }

    public string Name { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Biography { get; set; }

    public string Nationality { get; set; }

    public string PhotoUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual ICollection<MovieActor> MovieActors { get; set; } = new List<MovieActor>();

    public virtual ICollection<MovieDirector> MovieDirectors { get; set; } = new List<MovieDirector>();
}