// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Seat
{
    public int SeatId { get; set; }

    public int HallId { get; set; }

    public string RowNumber { get; set; }

    public int ColumnNumber { get; set; }

    public string SeatType { get; set; }

    public virtual ICollection<BookedSeat> BookedSeats { get; set; } = new List<BookedSeat>();

    public virtual CinemaHall Hall { get; set; }
}