// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Token
{
    public long TokenId { get; set; }

    public int UserId { get; set; }

    public string TokenValue { get; set; }

    public string TokenType { get; set; }

    public DateTime IssuedAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool IsRevoked { get; set; }

    public virtual User User { get; set; }
}