// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingTicketSysten.Models;

public partial class Vote
{
    public int VoteId { get; set; }

    public int UserId { get; set; }

    public int MovieId { get; set; }

    public int RatingValue { get; set; }

    public DateTime? VoteTime { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User User { get; set; }
}